### ISSUE TITLE
User Interface : De-selecting video track leaves filename as mkv

### ISSUE THREAD

**Issue by Kid-C** [mbunkus/mkvtoolnix#1761]
Issue (user interface/cosmetic):
Opening an mkv file in mkvtoolnix 9.3.1 and de-selecting the video track does not update the output file name to file type "mka." Subsequent processing via the "start muxing" button creates an mkv file without a video track.

Work-arounds:
1. Update the file name manually.

Screen shot:
https://www.dropbox.com/s/vhj3cszwk9ieivv/10_mmg_notes---no_vid_mkv.gif?dl=0

**Comment by remuxer32** [comment]
**@Kid-C**

This bug has been fixed. See, please: https://github.com/mbunkus/mkvtoolnix/issues/1743

I think you can close the issue.

**Comment by mbunkus** [comment]
Yeah, it's a duplicate.

**Comment by Kid-C** [comment]
Under 9.4.0, I still see this.

https://www.dropbox.com/s/uiiy9e1iv7kyh7l/10b_mmg_notes---no_vid_mkv%20%289.4.0%29.gif?dl=0

**Comment by mbunkus** [comment]
That behavior is intentional. As soon as the user changes the output file name from the default suggestion the GUI will stop messing around with it. I have no intentions of changing this.
